#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
#  AgentPay — Local Contract Deployment
#
#  Deploys PaymentChannel + ERC-8004 mock registries to Anvil.
#  Exports contract addresses to .env.local for agent startup.
#
#  Prerequisites: Foundry (forge, anvil, cast) installed
#
#  Usage:
#    ./scripts/deploy_local.sh
#    source .env.local  # load addresses into shell
# ─────────────────────────────────────────────────────────

set -euo pipefail

GREEN=$'\033[0;32m'
CYAN=$'\033[0;36m'
YELLOW=$'\033[1;33m'
BOLD=$'\033[1m'
NC=$'\033[0m'

echo "${BOLD}${CYAN}═══════════════════════════════════════════${NC}"
echo "${BOLD}  AgentPay — Local Contract Deployment${NC}"
echo "${CYAN}═══════════════════════════════════════════${NC}"

# ── Check prerequisites ────────────────────────────────
command -v forge >/dev/null 2>&1 || { echo "forge not found. Install Foundry: https://getfoundry.sh"; exit 1; }
command -v anvil >/dev/null 2>&1 || { echo "anvil not found. Install Foundry: https://getfoundry.sh"; exit 1; }
command -v cast  >/dev/null 2>&1 || { echo "cast not found. Install Foundry: https://getfoundry.sh"; exit 1; }

# ── Default Anvil private key (account 0) ──────────────
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
RPC_URL="http://127.0.0.1:8545"

# ── Check if Anvil is running ──────────────────────────
if ! cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
  echo "${YELLOW}Starting Anvil in background...${NC}"
  anvil --silent &
  ANVIL_PID=$!
  sleep 2
  echo "  Anvil PID: $ANVIL_PID"
else
  echo "${GREEN}Anvil already running${NC}"
  ANVIL_PID=""
fi

# ── Build contracts ────────────────────────────────────
echo ""
echo "${CYAN}Building contracts...${NC}"
cd contracts
[ -d lib/forge-std ] || git clone --depth 1 https://github.com/foundry-rs/forge-std.git lib/forge-std 2>/dev/null
forge build --silent

# ── Deploy ─────────────────────────────────────────────
echo "${CYAN}Deploying contracts...${NC}"
OUTPUT=$(forge script script/DeployAll.s.sol:DeployAllScript \
  --rpc-url "$RPC_URL" \
  --private-key "$DEPLOYER_KEY" \
  --broadcast 2>&1)

# Parse addresses from output
PAYMENT_CHANNEL=$(echo "$OUTPUT" | grep "PaymentChannel deployed" | grep -oP '0x[a-fA-F0-9]{40}')
IDENTITY_REGISTRY=$(echo "$OUTPUT" | grep "MockIdentityRegistry deployed" | grep -oP '0x[a-fA-F0-9]{40}')
REPUTATION_REGISTRY=$(echo "$OUTPUT" | grep "MockReputationRegistry deployed" | grep -oP '0x[a-fA-F0-9]{40}')

cd ..

# ── Write .env.local ───────────────────────────────────
cat > .env.local << EOF
# Generated by scripts/deploy_local.sh — $(date -Iseconds)
ETH_RPC_URL=$RPC_URL
PAYMENT_CHANNEL_ADDRESS=$PAYMENT_CHANNEL
ERC8004_IDENTITY_ADDRESS=$IDENTITY_REGISTRY
ERC8004_REPUTATION_ADDRESS=$REPUTATION_REGISTRY
DEPLOYER_KEY=$DEPLOYER_KEY
EOF

echo ""
echo "${GREEN}${BOLD}Deployment complete!${NC}"
echo ""
echo "  ${BOLD}PaymentChannel:${NC}        $PAYMENT_CHANNEL"
echo "  ${BOLD}IdentityRegistry:${NC}      $IDENTITY_REGISTRY"
echo "  ${BOLD}ReputationRegistry:${NC}    $REPUTATION_REGISTRY"
echo ""
echo "  Addresses written to ${BOLD}.env.local${NC}"
echo ""
echo "  Start agents with:"
echo "    ${CYAN}source .env.local${NC}"
echo "    ${CYAN}uv run agentpay start --eth-rpc \$ETH_RPC_URL --erc8004-identity \$ERC8004_IDENTITY_ADDRESS --erc8004-reputation \$ERC8004_REPUTATION_ADDRESS${NC}"

if [ -n "$ANVIL_PID" ]; then
  echo ""
  echo "  ${YELLOW}Anvil running as PID $ANVIL_PID (kill with: kill $ANVIL_PID)${NC}"
fi
